spring:
  application:
    name: "http-service2"

server:
  port: 8081

whatthecommit:
  url: "https://whatthecommit.com/index.txt"

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
