spring:
  application:
    name: "http-service1"

server:
  port: 8080

httpservice2:
  endpoint: "http://localhost:8081"

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
